version: '3.8'
services:
  mysqldb:
    image: "mysql:8.0.33"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: oyo_booking
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    volumes:
      - ./OYO_Booking_backend/backup/backup-data.sql:/docker-entrypoint-initdb.d/backup-data.sql
  backend:
    container_name: oyo_backend
    build: 
      context: ./OYO_Booking_backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mysqldb
  frontend:
    container_name: oyo_frontend
    build: 
      context: ./OYO_Booking_frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5174:5173
    depends_on:
      - backend

      